"""add tenant_id to request_logs

Revision ID: 1d215a5d311a
Revises: f173b14e6a38
Create Date: 2026-04-02 00:19:37.779641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d215a5d311a'
down_revision: Union[str, Sequence[str], None] = 'f173b14e6a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('tenant_id', sa.String(), nullable=True))
    op.execute("UPDATE request_logs SET tenant_id = 'legacy' WHERE tenant_id IS NULL")
    op.alter_column('request_logs', 'tenant_id', existing_type=sa.String(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_logs', 'tenant_id')
    # ### end Alembic commands ###
